version: "2"
linters:
  settings:
    errcheck:
      exclude-functions:
        # Used in HTTP handlers, any error is handled by the server itself.
        - (net/http.ResponseWriter).Write
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
