# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - main: ./cmd/subid-ldap/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - ppc64le
      - arm64
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{ .Version }}
      - -X github.com/prometheus/common/version.Revision={{ .FullCommit }}
      - -X github.com/prometheus/common/version.Branch={{ .Branch }}
      - -X github.com/prometheus/common/version.BuildUser=goreleaser
      - -X github.com/prometheus/common/version.BuildDate={{ .Date }}
archives:
  - id: archive
    files:
      - LICENSE
      - files/subid-ldap.service
checksum:
  name_template: 'checksums.txt'
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
